### ISSUE TITLE
[Question] Chrg&Dischrg Period Time

### ISSUE THREAD

**Issue by matomatusov** [wills106/homeassistant-solax-modbus#582]
Mandatory details:
1.Integration Version: 2023.11.1
2. HA Version: 2023.10.3
3. Inverter Brand: Solax X3 Gen4 10kW
4. Plugin Used: Solax Modbus
5. First 6 digits of Serial: H34A10
6. Connection Method: ModBus TCP using WaveShare RS485 TO ETH (B)

Why can't the step be set after minutes? In the SolaX Cloud app, this is set after minutes.
When you set 7:59 Charger End Time it will not appear in the SolaX integration.

![Chrg Dischrg Period_time](https://github.com/wills106/homeassistant-solax-modbus/assets/129114957/446857a0-865e-4d36-8045-240a2b6c0782)

**Comment by wills106** [comment]
Because it's coded as a select before the datetime and time entities for an Integration were possible.
To prevent the select from having 1440 possible selections it's coded to mostly only work on 15min intervals.

I haven't been able to successfully get time entities working yet.

It's listed under the Todo List V2 https://github.com/wills106/homeassistant-solax-modbus/discussions/200#discussioncomment-5891065

**Comment by matomatusov** [comment]
Thank you for the explanation.

**Comment by wills106** [comment]
If there is any successful progress it will be under the time branch https://github.com/wills106/homeassistant-solax-modbus/tree/time before a Beta goes out. I have put my work so far on that branch incase anyone knows what's missing to make it work.

**Comment by matomatusov** [comment]
Then I can test when it is available.
